ALTER TABLE users ADD COLUMN company_name VARCHAR(255) DEFAULT '' NOT NULL;
ALTER TABLE users ADD COLUMN designation VARCHAR(255) DEFAULT '' NOT NULL;
ALTER TABLE users ADD COLUMN department VARCHAR(255) DEFAULT '' NOT NULL;
ALTER TABLE users ADD COLUMN date_of_birth VARCHAR(255) DEFAULT '' NOT NULL;
